import type { DropdownName } from '@app/types';

export const DROPDOWN_DATA: Record<Exclude<DropdownName, ''>, string[]> = {
  AccountType: [
    'Public University',
    'Private University',
    'Community College',
    'Vocational School',
    'Online Learning Platform',
    'Educational Institution'
  ],
  ActionProType: [
    "Bachelor's Degree Program",
    "Master's Degree Program",
    'Doctoral Program',
    'Certificate Program',
    'Continuing Education'
  ],
  ActionType: [
    'Lecture',
    'Workshop',
    'Seminar',
    'Laboratory work',
    'Field trip',
    'Group project',
    'Individual assignment',
    'Research project',
    'Presentation',
    'Exam',
    'Online module',
    'Other'
  ],
  ChallengeFaced: [
    'Technical skills',
    'Financial resources',
    'Learning materials',
    'Student engagement',
    'Curriculum alignment',
    'Other'
  ],
  InitiativeStatus: ['Active', 'Completed'],
  RelationType: ['Parent', 'Child', 'Sibling', 'Partner', 'Related'],
  ReportStatus: [
    'Draft',
    'Submitted',
    'Under Review',
    'Graded',
    'Returned',
    'Published'
  ],
  TargetProgressTypes: [
    'On track',
    'At risk',
    'Behind schedule',
    'Completed',
    'Not started'
  ],
  TargetType: [
    'Knowledge acquisition',
    'Skill development',
    'Grade improvement',
    'Attendance rate',
    'Completion rate',
    'Student enrollment',
    'Course completion',
    'Student satisfaction',
    'Pass rate',
    'Research output',
    'Other',
    'Certification achievement',
    'Academic standards'
  ],
  TypesOfChallengesFaced: [
    'Technical skills',
    'Financial resources',
    'Learning materials',
    'Student engagement',
    'Curriculum alignment',
    'Other'
  ],
  Sessions: [
    'Fall Semester',
    'Spring Semester',
    'Summer Semester',
    'Winter Semester',
    'Academic Year',
    'Other'
  ],
  GoalAlignmentOther: [
    'Accreditation Standards',
    'Learning Outcomes',
    'Curriculum Framework',
    'Department Goals',
    'Other'
  ],
  Targets: [
    'Grade improvement',
    'Skill mastery',
    'Knowledge retention',
    'Student engagement',
    'Course completion',
    'Other'
  ],
  InitiativePrimaryFunctionTypes: [
    'Curriculum development',
    'Teaching',
    'Assessment and evaluation',
    'Student support',
    'Research and development',
    'Academic advising',
    'Other'
  ],
  ClimateFocusTypes: [
    'STEM',
    'Humanities',
    'Social Sciences',
    'Business',
    'Technology',
    'Professional Development',
    'Not applicable'
  ],
  GeographicalFocusTypes: [
    'Global',
    'Regional',
    'National',
    'Sub-national',
    'Local',
    'Transboundary'
  ],
  Countries: [
    'Algeria',
    'Egypt',
    'Libya',
    'Morocco',
    'Sudan',
    'Tunisia',
    'Burundi',
    'Comoros',
    'Djibouti',
    'Eritrea',
    'Ethiopia',
    'Kenya',
    'Madagascar',
    'Malawi',
    'Mauritius',
    'Mozambique',
    'Rwanda',
    'Seychelles',
    'Somalia',
    'South Sudan',
    'Uganda',
    'United Republic of Tanzania',
    'Zambia',
    'Zimbabwe',
    'Angola',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Congo',
    'Democratic Republic of the Congo',
    'Equatorial Guinea',
    'Gabon',
    'Sao Tome and Principe',
    'Botswana',
    'Eswatini',
    'Lesotho',
    'Namibia',
    'South Africa',
    'Benin',
    'Burkina Faso',
    'Cabo Verde',
    "Côte d'Ivoire",
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Liberia',
    'Mali',
    'Mauritania',
    'Niger',
    'Nigeria',
    'Senegal',
    'Sierra Leone',
    'Togo',
    'Antigua and Barbuda',
    'Bahamas',
    'Barbados',
    'Cuba',
    'Dominica',
    'Dominican Republic',
    'Grenada',
    'Haiti',
    'Jamaica',
    'Puerto Rico',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Trinidad and Tobago',
    'Belize',
    'Costa Rica',
    'El Salvador',
    'Guatemala',
    'Honduras',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Argentina',
    'Bolivia (Plurinational State of)',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela (Bolivarian Republic of)',
    'Canada',
    'United States of America',
    'Kazakhstan',
    'Kyrgyzstan',
    'Tajikistan',
    'Turkmenistan',
    'Uzbekistan',
    'China',
    "Democratic People's Republic of Korea",
    'Japan',
    'Mongolia',
    'Republic of Korea',
    'Brunei Darussalam',
    'Cambodia',
    'Indonesia',
    "Lao People's Democratic Republic",
    'Malaysia',
    'Myanmar',
    'Philippines',
    'Singapore',
    'Thailand',
    'Timor-Leste',
    'Viet Nam',
    'Afghanistan',
    'Bangladesh',
    'Bhutan',
    'India',
    'Iran (Islamic Republic of)',
    'Maldives',
    'Nepal',
    'Pakistan',
    'Sri Lanka',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Cyprus',
    'Georgia',
    'Iraq',
    'Israel',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Oman',
    'Qatar',
    'Saudi Arabia',
    'State of Palestine',
    'Syrian Arab Republic',
    'Türkiye',
    'United Arab Emirates',
    'Yemen',
    'Belarus',
    'Bulgaria',
    'Czechia',
    'Hungary',
    'Poland',
    'Republic of Moldova',
    'Romania',
    'Russian Federation',
    'Slovakia',
    'Ukraine',
    'Denmark',
    'Estonia',
    'Finland',
    'Iceland',
    'Ireland',
    'Latvia',
    'Lithuania',
    'Norway',
    'Sweden',
    'United Kingdom of Great Britain and Northern Ireland',
    'Albania',
    'Andorra',
    'Bosnia and Herzegovina',
    'Croatia',
    'Greece',
    'Holy See',
    'Italy',
    'Malta',
    'Montenegro',
    'North Macedonia',
    'Portugal',
    'San Marino',
    'Serbia',
    'Slovenia',
    'Spain',
    'Austria',
    'Belgium',
    'France',
    'Germany',
    'Liechtenstein',
    'Luxembourg',
    'Monaco',
    'Netherlands',
    'Switzerland',
    'Australia',
    'New Zealand',
    'Fiji',
    'Papua New Guinea',
    'Solomon Islands',
    'Vanuatu',
    'Kiribati',
    'Marshall Islands',
    'Micronesia (Federated States of)',
    'Nauru',
    'Palau',
    'Cook Islands',
    'Niue',
    'Samoa',
    'Tonga',
    'Tuvalu'
  ],
  IdentifyProviderType: ['B2C', 'Azure AD', 'Local Account'],
  BusinessActivities: [
    'Mathematics',
    'Science',
    'Engineering',
    'Computer Science',
    'Literature',
    'History',
    'Arts',
    'Other'
  ],
  BusinessRolesAssignment: [
    'Course Coordinator',
    'Instructor',
    'Teaching Assistant',
    'Department Head',
    'Associate Department Head',
    'Academic Advisor',
    'Associate Academic Advisor',
    'Subject Matter Expert',
    'Curriculum Specialist',
    'Assessment Coordinator',
    'Learning Outcomes Specialist',
    'Student Support Specialist',
    'Progress Reviewer',
    'Associate Progress Reviewer',
    'Progress Tracking Expert',
    'Academic Planning Expert',
    'Policy and Standards Expert',
    'Support Coordinator',
    'Associate Support Coordinator',
    'Student Services Expert'
  ],
  Regions: [
    'Africa',
    'Americas',
    'Asia',
    'Europe',
    'Oceania',
    'Northern Africa',
    'Eastern Africa',
    'Middle Africa',
    'Southern Africa',
    'Western Africa',
    'Latin America and the Caribbean',
    'Northern America',
    'Central Asia',
    'Eastern Asia',
    'South-eastern Asia',
    'Southern Asia',
    'Western Asia',
    'Eastern Europe',
    'Northern Europe',
    'Southern Europe',
    'Western Europe',
    'Australia and New Zealand',
    'Melanesia',
    'Micronesia',
    'Polynesia'
  ],
  MarrakechPartnershipThemes: [
    'Ocean and coastal zones',
    'Thematic focus not applicable',
    'Water',
    'Human settlements',
    'Transport',
    'Energy',
    'Industry',
    'Land-use'
  ],
  SustainableDevelopmentGoals: [
    'Goal 1. End poverty in all its forms everywhere',
    'Goal 10. Reduce inequality within and among countries',
    'Goal 11. Make cities and human settlements inclusive, safe, resilient and sustainable',
    'Goal 12. Ensure sustainable consumption and production patterns',
    'Goal 13. Take urgent action to combat climate change and its impacts',
    'Goal 14. Conserve and sustainably use oceans, seas & marine resources for sustainable development',
    'Goal 15. Protect, restore and promote sust use of terrestrial ecosystems, sustainably manage forests, combat deser',
    'Goal 16. Promote peaceful and inclusive societies for sust dev, provide access to justice',
    'Goal 17. Strengthen means of implementation and revitalize Global Partnership for Sust Dev Finance',
    'Goal 2. End hunger, achieve food security and improved nutrition and promote sustainable agriculture',
    'Goal 3. Ensure healthy lives and promote well-being for all at all ages',
    'Goal 4. Ensure inclusive & equit quality educ and promote lifelong learning opportunities for all',
    'Goal 5. Achieve gender equality and empower all women and girls',
    'Goal 6. Ensure availability and sustainable management of water and sanitation for all',
    'Goal 7. Ensure access to affordable, reliable, sustainable and modern energy for all',
    'Goal 8. Promote sustained, inclusive & sustainable economic growth, full & productive employment & decent work for al',
    'Goal 9. Build resilient infrastructure, promote inclusive & sust. industrialization & foster innov'
  ],
  Agreements: [
    'Vienna Convention for the Protection of the Ozone Layer and its Montreal Protocol on Substances that Deplete the Ozone Layer',
    'Kigali Amendment to the Montreal Protocol',
    'Convention on International Trade in Endangered Species of Wild Fauna and Flora (CITES)',
    'Convention on the Conservation of Migratory Species of Wild Animals (CMS)',
    'Agreement on the Conservation of African-Eurasian Migratory Waterbirds (AEWA)',
    'Agreement on the Conservation of Gorillas and their Habitats',
    'Agreement on the Conservation of Populations of European Bats (EUROBATS)',
    'Agreement on the Conservation of Small Cetaceans of the Baltic, North Atlantic, Irish and North Seas (ASCOBANS)',
    'Basel Convention on the Control of Transboundary Movements of Hazardous Wastes and their Disposal',
    'Rotterdam Convention on the Prior Informed Consent Procedure for Certain Hazardous Chemicals and Pesticides in International Trade',
    'Stockholm Convention on Persistent Organic Pollutants',
    'Minamata Convention on Mercury',
    'United Nations Convention to Combat Desertification (UNCCD)',
    'Convention on Biological Diversity (CBD)'
  ],
  SubNationalGovernmentType: [
    'Autonomous region',
    'State/Region/Provice',
    'City/Municipality',
    'Other'
  ],
  StaffingTypes: [
    'The Cooperative Climate Initiative does not have any dedicated staff',
    '1 to 10',
    '11 to 25',
    '26 to 50',
    'More than 50'
  ],
  SignatoriesAndMembers: [
    'Enrolled Students',
    'Registered Students',
    'We do not have students'
  ],
  SignatoryFollowUps: [
    'Students are required to directly submit assignments to the Course',
    'Students are required to submit assignments through a third-party platform',
    'The Course conducts regular assessments and evaluations',
    'The Course does not perform any follow-ups',
    'Other'
  ],
  Initiatives: [],
  CciRelationType: [
    'Parent program',
    'Component course',
    'Collaborative partnership with'
  ],
  CciRelationStatus: ['Yes', 'No', 'Pending'],
  InvolvedEntityType: [
    'Sponsoring Department',
    'Funding source',
    'Lead institution'
  ],
  ParticipantType: [
    'Full-time Student',
    'Part-time Student',
    'Graduate Student',
    'Undergraduate Student',
    'Continuing Education Student',
    'Audit Student',
    'Exchange Student'
  ],
  ParticipantCategory: ['Enrolled', 'Registered']
};
